In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Dataset/Social_Network_Ads.csv')
df

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [3]:
x = df[['Age','EstimatedSalary']]
y = df['Purchased']

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test , y_train,y_test = train_test_split(x_scaled,y,random_state=0)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [59]:
clf_log = LogisticRegression()
clf_dt = DecisionTreeClassifier(random_state=0)
clf_rf = RandomForestClassifier(random_state=0, n_estimators =10)
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_svm = SVC(random_state=0,kernel='rbf')
clf_nb = GaussianNB()

In [60]:
clf_log.fit(x_train,y_train)
clf_dt.fit(x_train,y_train)
clf_rf.fit(x_train,y_train)
clf_knn.fit(x_train,y_train)
clf_svm.fit(x_train,y_train)
clf_nb.fit(x_train,y_train);

In [61]:
y_pred1 = clf_log.predict(x_test)
y_pred2 = clf_dt.predict(x_test)
y_pred3 = clf_rf.predict(x_test)
y_pred4 = clf_knn.predict(x_test)
y_pred5 = clf_svm.predict(x_test)
y_pred6 = clf_nb.predict(x_test)

In [62]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report,ConfusionMatrixDisplay

In [63]:
# Logistic Regression
print('Log',accuracy_score(y_test,y_pred1))
print('Dt',accuracy_score(y_test,y_pred2))
print('rf',accuracy_score(y_test,y_pred3))
print('knn',accuracy_score(y_test,y_pred4))
print('svm',accuracy_score(y_test,y_pred5))
print('nb',accuracy_score(y_test,y_pred6))

Log 0.89
Dt 0.9
rf 0.93
knn 0.93
svm 0.93
nb 0.9


In [64]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report,ConfusionMatrixDisplay

In [65]:
print(confusion_matrix(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred5))
print(confusion_matrix(y_test,y_pred6))

[[67  1]
 [10 22]]
[[62  6]
 [ 4 28]]
[[64  4]
 [ 3 29]]
[[64  4]
 [ 3 29]]
[[64  4]
 [ 3 29]]
[[65  3]
 [ 7 25]]


In [66]:
print(classification_report(y_test,y_pred1))
print(classification_report(y_test,y_pred2))
print(classification_report(y_test,y_pred3))
print(classification_report(y_test,y_pred4))
print(classification_report(y_test,y_pred5))
print(classification_report(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92        68
           1       0.96      0.69      0.80        32

    accuracy                           0.89       100
   macro avg       0.91      0.84      0.86       100
weighted avg       0.90      0.89      0.88       100

              precision    recall  f1-score   support

           0       0.94      0.91      0.93        68
           1       0.82      0.88      0.85        32

    accuracy                           0.90       100
   macro avg       0.88      0.89      0.89       100
weighted avg       0.90      0.90      0.90       100

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

              preci

##### Create Voting Classifier

In [67]:
from sklearn.ensemble import VotingClassifier

In [68]:
vt = VotingClassifier(estimators=[('log', clf_log),
                                  ('ct', clf_dt),
                                  ('rf',clf_rf),
                                  ('knn',clf_knn),
                                  ('svm',clf_svm),
                                  ('nb',clf_nb)])

In [69]:
vt.fit(x_train,y_train)

VotingClassifier(estimators=[('log', LogisticRegression()),
                             ('ct', DecisionTreeClassifier(random_state=0)),
                             ('rf',
                              RandomForestClassifier(n_estimators=10,
                                                     random_state=0)),
                             ('knn', KNeighborsClassifier()),
                             ('svm', SVC(random_state=0)),
                             ('nb', GaussianNB())])

In [70]:
y_pred = vt.predict(x_test)

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report,ConfusionMatrixDisplay

In [72]:
accuracy_score(y_test,y_pred)

0.94

In [73]:
print(classification_report(y_test ,y_pred)) 

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        68
           1       0.91      0.91      0.91        32

    accuracy                           0.94       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.94      0.94      0.94       100



##### Apply Stacking

In [74]:
from sklearn.ensemble import StackingClassifier

In [75]:
stack = StackingClassifier(estimators=[('ct', clf_dt),
                                      ('rf',clf_rf),
                                      ('knn',clf_knn),
                                      ('svm',clf_svm),
                                      ('nb',clf_nb)],
                                      final_estimator = clf_log)

In [76]:
stack.fit(x_train,y_train)

StackingClassifier(estimators=[('ct', DecisionTreeClassifier(random_state=0)),
                               ('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=0)),
                               ('knn', KNeighborsClassifier()),
                               ('svm', SVC(random_state=0)),
                               ('nb', GaussianNB())],
                   final_estimator=LogisticRegression())

In [77]:
y_predi = stack.predict(x_test)

In [78]:
accuracy_score(y_test,y_pred)

0.94

In [79]:
print(classification_report(y_test ,y_pred)) 

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        68
           1       0.91      0.91      0.91        32

    accuracy                           0.94       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.94      0.94      0.94       100



In [80]:
stack = StackingClassifier(estimators=[('ct', clf_dt),
                                      ('rf',clf_rf),
                                      ('knn',clf_knn),
                                      ('log',clf_log),
                                      ('nb',clf_nb)],
                                      final_estimator = clf_svm)

In [81]:
stack.fit(x_train,y_train)

StackingClassifier(estimators=[('ct', DecisionTreeClassifier(random_state=0)),
                               ('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=0)),
                               ('knn', KNeighborsClassifier()),
                               ('log', LogisticRegression()),
                               ('nb', GaussianNB())],
                   final_estimator=SVC(random_state=0))

In [82]:
y_predi = stack.predict(x_test)

In [86]:
accuracy_score(y_test,y_predi)

0.93

In [87]:
print(classification_report(y_test ,y_predi)) 

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

